language: scala
compiler: gcc
sudo: false
scala:
  - 2.11.4
script: java -Xms1536m -Xmx1536m -Xss30m -XX:MaxPermSize=384m -XX:ReservedCodeCacheSize=192m -jar sbt-launch.jar coverage test
after_success: "sbt coveralls"
